import React from 'react'

const Admin = () => {
  return (
    <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam quas, ratione et recusandae ex impedit amet possimus a numquam voluptate incidunt totam nostrum aut, optio id, libero expedita. 
            Molestias ipsam expedita aliquid, dicta dolorem sit maiores sapiente consequatur ratione in dolor, rerum provident. Repellendus odio iusto commodi cumque obcaecati qui cupiditate voluptates in quae, quis, animi voluptatum soluta nulla fuga aspernatur illum eum eveniet! 
            Ad, earum velit dolorem consectetur eaque architecto suscipit soluta minima obcaecati porro. Corporis, fuga officiis ut adipisci suscipit molestiae animi esse eum voluptates quaerat quisquam saepe. At eum voluptate illum alias ipsum consequuntur! Nostrum id, quos magni, nihil neque, iusto assumenda officia autem adipisci molestiae necessitatibus veniam vel nobis ducimus deleniti hic fugiat vero provident quam veritatis. 
            Qui odit aliquam rem exercitationem nulla voluptatem facilis alias ratione suscipit fuga consequuntur commodi sapiente perferendis repudiandae cum eaque veniam obcaecati placeat doloremque architecto libero magnam veritatis, molestias illum! Adipisci eos eius distinctio quisquam laborum numquam voluptatum incidunt eum cupiditate, dolorem quo ut quam, minima sed, aut perspiciatis porro. Dolorem earum optio molestiae similique. 
            Veritatis numquam dignissimos architecto adipisci harum porro placeat earum tenetur, quam officia blanditiis, quae repudiandae nulla error animi pariatur expedita, voluptas culpa? Magni, earum! Quam accusantium ratione incidunt molestias aut dignissimos ex voluptatibus voluptas maiores, inventore cupiditate quia explicabo nisi similique ullam perferendis modi perspiciatis! Eveniet mollitia odit sapiente nesciunt illum hic deleniti et, est rem? Officia, sint incidunt ullam quas repellat ratione laudantium dolore debitis magni esse harum? Totam omnis deleniti voluptate adipisci ut ullam, veniam vitae tempore debitis, dignissimos nisi voluptas illo beatae eius, quo iure magni. At modi ipsum quas totam hic vero soluta itaque maiores odio libero pariatur quibusdam incidunt voluptatem ex quisquam nesciunt blanditiis quos accusamus a iste, nostrum laudantium voluptatibus possimus maxime? Quos exercitationem, illum quas dolores tempora dolore porro laborum quam sit impedit quis repellendus laudantium odit repellat officiis ullam? Id autem laudantium ducimus dolorem omnis praesentium exercitationem tenetur, nobis nemo quas cumque molestiae laborum veniam ab aliquid tempora perferendis aliquam doloribus tempore aut numquam ratione. Dolorem cumque laborum enim nihil, quibusdam numquam in quam, excepturi repellat, soluta illum impedit. Totam impedit magnam iure possimus, voluptate culpa odit, itaque facilis molestiae modi, quasi laboriosam reiciendis corporis! Numquam vero, harum beatae repellat quis sit ex dolorem, 
            pariatur praesentium obcaecati laudantium expedita, ducimus suscipit commodi consequatur adipisci doloribus tenetur culpa neque ipsam temporibus quas libero? 
            Corporis, porro cumque nisi, laboriosam dolores inventore aspernatur tempora saepe tempore nulla deserunt voluptates cum facere possimus velit est deleniti enim consectetur ipsam accusamus sequi laudantium perferendis? Sunt voluptates excepturi tempore corporis vitae tempora, quo exercitationem. Dignissimos voluptas, asperiores, mollitia, nam fugit atque ducimus labore animi possimus in nesciunt vitae nisi quod culpa ab corporis perferendis! Atque, sunt voluptate qui illum saepe eveniet expedita non earum temporibus labore, exercitationem, suscipit dolorem dolor modi in. Expedita numquam quia vero cumque veniam esse explicabo, praesentium adipisci pariatur voluptatibus voluptatem dolorum! Dolores totam quis, illo fugiat labore architecto quisquam deserunt aperiam animi esse cumque, dolorem necessitatibus temporibus ipsam?</p>
    </div>
  )
}

export default Admin